### ISSUE TITLE
HTMLImageElement is not defined

### ISSUE THREAD

**Issue by kleinjm** [zhanziyang/vue-croppa#29] opened 2017-09-21 18:57 UTC
Using the very basic
```
import Vue from 'vue';
import Croppa from 'vue-croppa';
Vue.use(Croppa);
```
I'm seeing the following stack trace upon booting the app. Is `HTMLImageElement` a native object type of Vue or is that something in your library specifically. I can't find much on it and it looks like the only place you use it is the `initial-image` option. Seems like a great library, would love to get this working.

```
Call Stack: ReferenceError: HTMLImageElement is not defined
    at .../node_modules/vue-croppa/dist/vue-croppa.js:389:26
    at commonjsGlobal (.../node_modules/vue-croppa/dist/vue-croppa.js:10:82)
    at Object. (.../node_modules/vue-croppa/dist/vue-croppa.js:13:2)
    at Module._compile (module.js:624:30)
    at Object.Module._extensions.(anonymous function) [as .js] (.../node_modules/node-hook/index.js:73:14)
    at Module.load (module.js:545:32)
```

**Comment by kleinjm** [comment] 2017-09-21 21:55
Needed to mount it a bit different in my build environment
```
  export default {
    components: {
      croppa: Croppa.component
    },
```

**Comment by zhanziyang** [comment] 2017-09-22 02:08
It's really weird because HTMLImageElement is a native object contructor of browsers and I think all browsers support it. It might be a problem with SSR though. I will fix it by adding an "if" before using it. Thank you for reporting this!

**Comment by zhanziyang** [comment] 2017-09-27 12:42
Fixed in new released version v1.0.0.

**Comment by SebastianBar** [comment] 2017-11-28 13:36
@kleinjm were you trying to use Croppa with Nuxt? I'm trying to make it work, and despite disabling SSR for this specific component, it doesn't want to work properly (sometimes it works, sometimes it doesn't bind to the specified v-model and fails to get blobs)

**Comment by kleinjm** [comment] 2017-11-28 13:58
@SebastianBar no unfortunately I wasn't using it with Nuxt and my second post above was all I need to fix my issue. Good luck!

**Comment by SebastianBar** [comment] 2017-11-30 03:03
Since it was binding and sometimes not, I had to do a workaround.

I removed the v-model binding for croppa components, because it wasn't consistent.
Then I had to check every croppa component in order to obtain blobs.

Not the way it's supposed to work, but it does the trick!

**Comment by zhanziyang** [comment] 2017-12-01 14:50
Hi @SebastianBar 

>  sometimes it doesn't bind to the specified v-model and fails to get blobs

Is there any error on console?

I can not reproduce the problem you describe. Can you provide a demo or some source code of your project?

**Closed** 2018-01-28 01:20 UTC
